version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby
    steps:
      - checkout
      - run: echo "run build!!"
  test:
    docker:
      - image: circleci/ruby
    steps:
      - checkout
      - run: echo "run test!!"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
